export const MAJOR_LENDERS = [
  'Black Horse (Lloyds Banking Group)',
  'Barclays Partner Finance',
  'Close Brothers Motor Finance',
  'FirstRand (MotoNovo Finance)',
  'Santander Consumer Finance',
  'Volkswagen Financial Services',
  'BMW Financial Services',
  'Mercedes-Benz Financial Services',
  'Toyota Financial Services',
  'Ford Credit',
  'Vauxhall Finance',
  'Peugeot Finance',
  'Renault Finance',
  'Nissan Finance',
  'Kia Finance',
  'Hyundai Finance',
  'Alphera Financial Services (BMW Group)',
  'Oodle Car Finance',
  'Blue Motor Finance',
  'Zopa',
  'Hitachi Capital',
  'ALPHERA Financial Services',
  'Startline Motor Finance',
  'Advantage Finance',
  'Other',
];
